Ax 101 make initial api call and load required data
Abstractolotl/azplace-frontend pull request #16
Opened 2022-08-01 12:20 UTC by Arekkus

2022-08-01 13:22 UTC, Ancocodet commented on src/config.json
> +  "API_BASE_URL": "https://api.azplace.azubi.server.lan/api"
without /api at the end

2022-08-01 13:23 UTC, Ancocodet requested changes

2022-08-01 13:23 UTC, Ancocodet commented on src/config.json
> +  "API_BASE_URL": "https://api.azplace.azubi.server.lan/api"
without /api at the end

2022-08-02 13:48 UTC, Ancocodet approved these changes

2022-08-02 14:15 UTC, NouCake commented on src/App.vue
> +axios.get("http://www.randomnumberapi.com/api/v1.0/random?min=1&max=500&count=1")
debug code raus wenn in master gepusht wird.

2022-08-02 14:20 UTC, NouCake commented on src/App.vue
> -axios.get(config.API_GET_BOARD_INFO)
kein auskommentierter code

2022-08-02 14:20 UTC, NouCake commented on src/components/LiveCanvas.vue
> +      <canvas v-if="store.state.canvasInfo.width != 0" ref="htmlCanvas"></canvas>
nicht über width != 0.

canvasInfo soll null sein wenn kein Board geladen ist.

2022-08-02 14:20 UTC, NouCake commented on src/components/LiveCanvas.vue
> +  loadMockData();
einrückung

2022-08-02 14:20 UTC, NouCake commented on src/components/LiveCanvas.vue
> +			ctx.fillStyle = store.state.canvasInfo.colors[/*index*/ createNoise()].toString();
auskommentierter debug code

2022-08-02 14:20 UTC, NouCake commented on src/components/LiveCanvas.vue
>  	store.state.canvas = {
ist das nicht mittlerweile canvasInfo?

2022-08-02 14:20 UTC, NouCake commented on src/types.ts
> +    canvasInfo: CanvasInfo,
why?

2022-08-02 14:20 UTC, NouCake commented on src/types.ts
> +    randomNumber: String
nope

2022-08-02 14:20 UTC, NouCake commented on src/types.ts
> +export interface CanvasInfo {
Dafür existiert doch der Board Type...
warum nochmal das selbe unter anderem Namen?

2022-08-05 09:50 UTC, closed without merging