AX-55 Implement live canvas
Abstractolotl/azplace-frontend pull request #5
Opened 2022-07-26 11:29 UTC by jonasrdl

2022-07-26 11:33 UTC, NouCake commented on src/components/LiveCanvas.vue
> +const store: Store<any> = useStore();
kein any.
Das interface definieren!

2022-07-26 11:33 UTC, NouCake commented on src/components/LiveCanvas.vue
> +  const c = document.getElementById('canvas') as HTMLCanvasElement;
aussagekrätige namen verwenden

2022-07-26 11:37 UTC, NouCake requested changes

2022-07-26 11:37 UTC, NouCake commented on src/components/LiveCanvas.vue
> +  let ctx: CanvasRenderingContext2D | null = c.getContext("2d");
warum hier nicht die schreibweiße wie oben mit as?

2022-07-26 11:37 UTC, NouCake commented on src/components/LiveCanvas.vue
> +  ctx.stroke();
braucht man nicht?

2022-07-26 11:37 UTC, NouCake commented on src/components/LiveCanvas.vue
> +  zoomLevel += event.deltaY * -0.01;
würd den multiplier rausnehmen und als const ablegen

2022-07-26 13:58 UTC, Ancocodet approved these changes

2022-07-26 14:02 UTC, NouCake approved these changes

2022-07-27 08:11 UTC, lucaspape approved these changes
lgtm

2022-07-27 08:11 UTC, Ancocodet approved these changes

2022-07-27 08:13 UTC, merged